# Generated by Django 4.0.6 on 2022-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebus', '0002_alter_location_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('threshold', models.IntegerField(default=25, help_text='Accepted distance in meters from point')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeNumberProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.FloatField()),
                ('threshold', models.IntegerField(default=0, help_text='Accepted distance from correct answer, in percent. If correct_answer is 0, the distance is treated as if it was 1')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTextProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=100)),
                ('threshold', models.IntegerField(default=0, help_text='Accepted Levenshtein distance between given and correct answer. 0 for only exact answers')),
            ],
        ),
        migrations.CreateModel(
            name='OpenProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='hidden_title',
            field=models.CharField(default='Teigen-statua', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default='Hvem er dette?', max_length=50),
            preserve_default=False,
        ),
    ]
