# Generated by Django 4.0.6 on 2022-07-19 21:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebus', '0004_geoproblem_location_knowledgenumberproblem_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoproblem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geoproblem',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgenumberproblem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgenumberproblem',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgetextproblem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowledgetextproblem',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openproblem',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openproblem',
            name='title',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
