# Generated by Django 4.1 on 2022-08-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebus', '0008_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='player',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
